sonar.projectName=TorreTechTest
sonar.sourceEncoding=UTF-8

sonar.sources=backend/src/main/java,frontend/src
sonar.tests=backend/src/test/java

sonar.java.binaries=backend/target/classes
sonar.java.test.binaries=backend/target/test-classes
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml

sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/build/**,**/coverage/**,**/public/**,**/*.config.js,**/*.config.mjs,**/*.config.ts,**/*.ico,**/tailwind.config.ts,**/postcss.config.mjs,**/next.config.ts,backend/target/**,frontend/.vercel/**,frontend/vercel.json
