services:
  - type: web
    name: torre-tech-test-backend
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/techtest-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_OPTS
        value: -Xmx512m
      - key: SERVER_PORT
        value: 8080
    plan: free
